# Lab Assignment 2: How to Load CSV, ASCII, and other data into Python
## DS 6001: Practice and Application of Data Science

### Instructions
Please answer the following questions as completely as possible using text, code, and the results of code as needed. Format your answers in a Jupyter notebook. To receive full credit, make sure you address every part of the problem, and make sure your document is formatted in a clean and professional way.

There are 11 data files attached to this lab assignment, with different extensions. First, download all of these data files, and save them in the same folder on your local machine. Your task in the following questions is to load each file into Python correctly, so that you can begin the process of data cleaning. If the variable names are included in the file, use those names to name the columns. If the variable names are not included, use these names in order:

In [3]:
column_names = ["Country", "Happiness score", "Whisker-high", "Whisker-low", 
  "Dystopia (1.92) + residual", "Explained by: GDP per capita", 
  "Explained by: Social support", "Explained by: Healthy life expectancy", 
  "Explained by: Freedom to make life choices", "Explained by: Generosity", 
  "Explained by: Perceptions of corruption" ]

If you loaded the data correctly, it will look like `data_clean.csv`, which is also attached to this lab.

## Problem 0
Import the libraries you will need. Then write code to change the working directory to the folder in which you saved the data files, run the code displayed above to create the `column_names` list, load `data_clean.csv`, and display the output of the `.info()` method of `data_clean`. (1 point)

In [54]:
# load libraries
import numpy as np
import pandas as pd
import os
import sys
sys.tracebacklimit = 0

# change working directory
oldpath = os.getcwd()
os.chdir("/Users/Clair/Downloads/lab data")

# read in file
clean_data = pd.read_csv("data_clean.csv")

# create column_names list
column_names = ["Country", "Happiness score", "Whisker-high", "Whisker-low", 
  "Dystopia (1.92) + residual", "Explained by: GDP per capita", 
  "Explained by: Social support", "Explained by: Healthy life expectancy", 
  "Explained by: Freedom to make life choices", "Explained by: Generosity", 
  "Explained by: Perceptions of corruption" ]

# display .info output
print(clean_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 11 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     156 non-null    object
 1   Happiness score                             156 non-null    float64
 2   Whisker-high                                156 non-null    float64
 3   Whisker-low                                 156 non-null    float64
 4   Dystopia (1.92) + residual                  156 non-null    float64
 5   Explained by: GDP per capita                156 non-null    float64
 6   Explained by: Social support                156 non-null    float64
 7   Explained by: Healthy life expectancy       156 non-null    float64
 8   Explained by: Freedom to make life choices  156 non-null    float64
 9   Explained by: Generosity                    156 non-null    float64
 10  Explained by: Perceptions of corruption     156 non-null    float64
dtypes: float64(10), object(1)
memory usage: 13.5+ KB
None

## Problem 1
Load `data1.csv`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (1 point)

In [56]:
data1 = pd.read_csv("data1.csv", skiprows=2) # read in file

pd.set_option('display.max_columns', 10) # display max 10 columns
pd.set_option('display.max_rows', 10) # display max 10 rows

display(data1.head(10)) # display first 10 rows
display(data1.tail(10)) # display last 10 rows
display(data1.describe()) # display descriptive statistics about data

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,...,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,...,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357
5,Netherlands,7.441,7.498,7.384,2.448,...,1.488,0.878,0.638,0.333,0.295
6,Canada,7.328,7.421,7.236,2.306,...,1.532,0.896,0.653,0.321,0.291
7,New Zealand,7.324,7.401,7.247,2.156,...,1.601,0.876,0.669,0.365,0.389
8,Sweden,7.314,7.388,7.241,2.217,...,1.501,0.913,0.659,0.285,0.383
9,Australia,7.272,7.358,7.186,2.139,...,1.573,0.910,0.647,0.361,0.302

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
146,Malawi,3.587,3.691,3.482,1.732,...,0.541,0.306,0.531,0.210,0.080
147,Haiti,3.582,3.713,3.451,1.744,...,0.714,0.289,0.025,0.392,0.104
148,Liberia,3.495,3.623,3.368,1.640,...,0.858,0.267,0.419,0.206,0.030
149,Syria,3.462,3.664,3.260,1.244,...,0.382,0.539,0.088,0.376,0.144
150,Rwanda,3.408,3.500,3.317,0.500,...,0.896,0.400,0.636,0.200,0.444
151,Yemen,3.355,3.448,3.262,1.106,...,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,...,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,...,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,...,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,...,0.627,0.145,0.065,0.149,0.076

,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,5.375878,5.478654,5.273090,1.922891,0.887417,1.216571,0.598026,0.456981,0.181571,0.112474
std,1.119507,1.107522,1.132544,0.513760,0.382573,0.300380,0.247925,0.162750,0.098805,0.096362
min,2.905000,3.074000,2.735000,0.292000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.453750,4.589750,4.344750,1.654250,0.616250,1.076750,0.422250,0.358250,0.109500,0.051000
50%,5.378000,5.477500,5.284500,1.908500,0.949500,1.261500,0.644000,0.494000,0.174000,0.082000
75%,6.168500,6.260000,6.051250,2.270250,1.197750,1.463000,0.777250,0.580000,0.242250,0.139000
max,7.632000,7.695000,7.569000,2.961000,1.649000,1.644000,1.030000,0.724000,0.598000,0.457000

The first two lines of the dataset have some funky commenting, but that can easily be addressed by adding either ``header=2`` or ``skiprows=2`` to ``pd.read_csv``.

## Problem 2
Load `data2.txt`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (1 point)

In [6]:
data2 = pd.read_csv("data2.txt", skiprows=2, comment="/") # read in file with updated parameter

display(data2.head(10)) # display first 10 rows
display(data2.tail(10)) # display last 10 rows
display(data2.describe())

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,...,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,...,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357
5,Netherlands,7.441,7.498,7.384,2.448,...,1.488,0.878,0.638,0.333,0.295
6,Canada,7.328,7.421,7.236,2.306,...,1.532,0.896,0.653,0.321,0.291
7,New Zealand,7.324,7.401,7.247,2.156,...,1.601,0.876,0.669,0.365,0.389
8,Sweden,7.314,7.388,7.241,2.217,...,1.501,0.913,0.659,0.285,0.383
9,Australia,7.272,7.358,7.186,2.139,...,1.573,0.910,0.647,0.361,0.302

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
146,Malawi,3.587,3.691,3.482,1.732,...,0.541,0.306,0.531,0.210,0.080
147,Haiti,3.582,3.713,3.451,1.744,...,0.714,0.289,0.025,0.392,0.104
148,Liberia,3.495,3.623,3.368,1.640,...,0.858,0.267,0.419,0.206,0.030
149,Syria,3.462,3.664,3.260,1.244,...,0.382,0.539,0.088,0.376,0.144
150,Rwanda,3.408,3.500,3.317,0.500,...,0.896,0.400,0.636,0.200,0.444
151,Yemen,3.355,3.448,3.262,1.106,...,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,...,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,...,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,...,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,...,0.627,0.145,0.065,0.149,0.076

,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,5.375878,5.478654,5.273090,1.922891,0.887417,1.216571,0.598026,0.456981,0.181571,0.112474
std,1.119507,1.107522,1.132544,0.513760,0.382573,0.300380,0.247925,0.162750,0.098805,0.096362
min,2.905000,3.074000,2.735000,0.292000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.453750,4.589750,4.344750,1.654250,0.616250,1.076750,0.422250,0.358250,0.109500,0.051000
50%,5.378000,5.477500,5.284500,1.908500,0.949500,1.261500,0.644000,0.494000,0.174000,0.082000
75%,6.168500,6.260000,6.051250,2.270250,1.197750,1.463000,0.777250,0.580000,0.242250,0.139000
max,7.632000,7.695000,7.569000,2.961000,1.649000,1.644000,1.030000,0.724000,0.598000,0.457000

The funky commenting in the first two rows is present here as well, but it's accompanied by some commenting within the dataitself. The comments at the top can be removed with ``skiprows=2`` and the commenting within by adding the ``comment="/"`` parameter to ``pd.read_csv``.

## Problem 3
Load `data3.txt`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (1 point)

In [7]:
data3 = pd.read_csv("data3.txt", skiprows=2, sep="\t") # read in file

display(data3.head(10)) # display first 10 rows
display(data3.tail(10)) # display last 10 rows
display(data3.describe())

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,...,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,...,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357
5,Netherlands,7.441,7.498,7.384,2.448,...,1.488,0.878,0.638,0.333,0.295
6,Canada,7.328,7.421,7.236,2.306,...,1.532,0.896,0.653,0.321,0.291
7,New Zealand,7.324,7.401,7.247,2.156,...,1.601,0.876,0.669,0.365,0.389
8,Sweden,7.314,7.388,7.241,2.217,...,1.501,0.913,0.659,0.285,0.383
9,Australia,7.272,7.358,7.186,2.139,...,1.573,0.910,0.647,0.361,0.302

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
146,Malawi,3.587,3.691,3.482,1.732,...,0.541,0.306,0.531,0.210,0.080
147,Haiti,3.582,3.713,3.451,1.744,...,0.714,0.289,0.025,0.392,0.104
148,Liberia,3.495,3.623,3.368,1.640,...,0.858,0.267,0.419,0.206,0.030
149,Syria,3.462,3.664,3.260,1.244,...,0.382,0.539,0.088,0.376,0.144
150,Rwanda,3.408,3.500,3.317,0.500,...,0.896,0.400,0.636,0.200,0.444
151,Yemen,3.355,3.448,3.262,1.106,...,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,...,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,...,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,...,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,...,0.627,0.145,0.065,0.149,0.076

,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,5.375878,5.478654,5.273090,1.922891,0.887417,1.216571,0.598026,0.456981,0.181571,0.112474
std,1.119507,1.107522,1.132544,0.513760,0.382573,0.300380,0.247925,0.162750,0.098805,0.096362
min,2.905000,3.074000,2.735000,0.292000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.453750,4.589750,4.344750,1.654250,0.616250,1.076750,0.422250,0.358250,0.109500,0.051000
50%,5.378000,5.477500,5.284500,1.908500,0.949500,1.261500,0.644000,0.494000,0.174000,0.082000
75%,6.168500,6.260000,6.051250,2.270250,1.197750,1.463000,0.777250,0.580000,0.242250,0.139000
max,7.632000,7.695000,7.569000,2.961000,1.649000,1.644000,1.030000,0.724000,0.598000,0.457000

At first, the values were separated with ``"\t"`` instead of ``","`` but it was fixed with the ``sep="\t`` parameter of ``read_csv()``. However, funky commenting at the header remained, so the ``skiprows=2`` parameter finished it off.

## Problem 4
Load `data4.txt`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (1 point)

In [8]:
data4 = pd.read_csv("data4.txt", names=column_names, sep="$") # read in file

display(data4.head(10)) # display first 10 rows
display(data4.tail(10)) # display last 10 rows
display(data4.describe())

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,...,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,...,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357
5,Netherlands,7.441,7.498,7.384,2.448,...,1.488,0.878,0.638,0.333,0.295
6,Canada,7.328,7.421,7.236,2.306,...,1.532,0.896,0.653,0.321,0.291
7,New Zealand,7.324,7.401,7.247,2.156,...,1.601,0.876,0.669,0.365,0.389
8,Sweden,7.314,7.388,7.241,2.217,...,1.501,0.913,0.659,0.285,0.383
9,Australia,7.272,7.358,7.186,2.139,...,1.573,0.910,0.647,0.361,0.302

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
146,Malawi,3.587,3.691,3.482,1.732,...,0.541,0.306,0.531,0.210,0.080
147,Haiti,3.582,3.713,3.451,1.744,...,0.714,0.289,0.025,0.392,0.104
148,Liberia,3.495,3.623,3.368,1.640,...,0.858,0.267,0.419,0.206,0.030
149,Syria,3.462,3.664,3.260,1.244,...,0.382,0.539,0.088,0.376,0.144
150,Rwanda,3.408,3.500,3.317,0.500,...,0.896,0.400,0.636,0.200,0.444
151,Yemen,3.355,3.448,3.262,1.106,...,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,...,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,...,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,...,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,...,0.627,0.145,0.065,0.149,0.076

,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,5.375878,5.478654,5.273090,1.922891,0.887417,1.216571,0.598026,0.456981,0.181571,0.112474
std,1.119507,1.107522,1.132544,0.513760,0.382573,0.300380,0.247925,0.162750,0.098805,0.096362
min,2.905000,3.074000,2.735000,0.292000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.453750,4.589750,4.344750,1.654250,0.616250,1.076750,0.422250,0.358250,0.109500,0.051000
50%,5.378000,5.477500,5.284500,1.908500,0.949500,1.261500,0.644000,0.494000,0.174000,0.082000
75%,6.168500,6.260000,6.051250,2.270250,1.197750,1.463000,0.777250,0.580000,0.242250,0.139000
max,7.632000,7.695000,7.569000,2.961000,1.649000,1.644000,1.030000,0.724000,0.598000,0.457000

The data in this file was separated by dollar signs rather than commas, and the columns were not named. To fix these issues, ``sep="$"`` and ``names=column_names`` were added as parameters to ``read_csv()``.

## Problem 5
Load `data5.csv`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (1 point)

In [51]:
data5 = pd.read_csv("data5.csv", skipfooter=2) # read in file

display(data5.head(10)) # display first 10 rows
display(data5.tail(10)) # display last 10 rows
display(data5.describe())

/Users/Clair/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,...,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,...,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357
5,Netherlands,7.441,7.498,7.384,2.448,...,1.488,0.878,0.638,0.333,0.295
6,Canada,7.328,7.421,7.236,2.306,...,1.532,0.896,0.653,0.321,0.291
7,New Zealand,7.324,7.401,7.247,2.156,...,1.601,0.876,0.669,0.365,0.389
8,Sweden,7.314,7.388,7.241,2.217,...,1.501,0.913,0.659,0.285,0.383
9,Australia,7.272,7.358,7.186,2.139,...,1.573,0.910,0.647,0.361,0.302

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
146,Malawi,3.587,3.691,3.482,1.732,...,0.541,0.306,0.531,0.210,0.080
147,Haiti,3.582,3.713,3.451,1.744,...,0.714,0.289,0.025,0.392,0.104
148,Liberia,3.495,3.623,3.368,1.640,...,0.858,0.267,0.419,0.206,0.030
149,Syria,3.462,3.664,3.260,1.244,...,0.382,0.539,0.088,0.376,0.144
150,Rwanda,3.408,3.500,3.317,0.500,...,0.896,0.400,0.636,0.200,0.444
151,Yemen,3.355,3.448,3.262,1.106,...,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,...,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,...,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,...,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,...,0.627,0.145,0.065,0.149,0.076

,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,5.375878,5.478654,5.273090,1.922891,0.887417,1.216571,0.598026,0.456981,0.181571,0.112474
std,1.119507,1.107522,1.132544,0.513760,0.382573,0.300380,0.247925,0.162750,0.098805,0.096362
min,2.905000,3.074000,2.735000,0.292000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.453750,4.589750,4.344750,1.654250,0.616250,1.076750,0.422250,0.358250,0.109500,0.051000
50%,5.378000,5.477500,5.284500,1.908500,0.949500,1.261500,0.644000,0.494000,0.174000,0.082000
75%,6.168500,6.260000,6.051250,2.270250,1.197750,1.463000,0.777250,0.580000,0.242250,0.139000
max,7.632000,7.695000,7.569000,2.961000,1.649000,1.644000,1.030000,0.724000,0.598000,0.457000

``read_csv`` opened the file, but dataset had a bit of funky commenting in the footer, so the ``skipfooter=2`` parameter was added to remove the commenting. However, even though it worked, this parameter raised an exception.

## Problem 6
Load `data6.dat`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (1 point)

In [50]:
data6 = pd.read_csv("data6.dat", na_values=999) # read in file

display(data6.head(10)) # display first 10 rows
display(data6.tail(10)) # display last 10 rows
display(data6.describe())

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,NaN,NaN,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,NaN,...,1.582,NaN,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,NaN,0.683,0.284,0.408
3,Iceland,7.495,7.593,NaN,2.426,...,1.644,0.914,0.677,0.353,NaN
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357
5,Netherlands,7.441,7.498,7.384,2.448,...,1.488,0.878,0.638,0.333,NaN
6,Canada,7.328,7.421,7.236,2.306,...,1.532,0.896,0.653,0.321,0.291
7,New Zealand,7.324,7.401,7.247,NaN,...,1.601,0.876,0.669,0.365,0.389
8,Sweden,7.314,7.388,7.241,2.217,...,1.501,0.913,0.659,NaN,0.383
9,Australia,7.272,NaN,7.186,2.139,...,1.573,0.910,0.647,0.361,0.302

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
146,Malawi,3.587,NaN,3.482,1.732,...,NaN,0.306,0.531,NaN,0.080
147,Haiti,NaN,3.713,3.451,1.744,...,0.714,0.289,NaN,0.392,0.104
148,Liberia,3.495,3.623,3.368,1.640,...,0.858,0.267,0.419,0.206,0.030
149,Syria,3.462,3.664,3.260,1.244,...,0.382,0.539,0.088,0.376,0.144
150,Rwanda,NaN,3.500,3.317,0.500,...,0.896,NaN,0.636,0.200,0.444
151,NaN,3.355,3.448,3.262,1.106,...,1.073,0.343,0.244,NaN,0.064
152,Tanzania,NaN,NaN,3.193,0.628,...,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,NaN,3.123,1.691,...,NaN,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,...,0.000,0.010,0.305,NaN,0.038
155,Burundi,2.905,3.074,NaN,1.752,...,NaN,0.145,0.065,0.149,0.076

,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
count,142.000000,135.000000,136.000000,145.000000,137.000000,134.000000,142.000000,140.000000,145.000000,143.000000
mean,5.459296,5.501526,5.345412,1.922241,0.900577,1.226739,0.590803,0.455450,0.182517,0.113035
std,1.120187,1.104762,1.134021,0.514837,0.374956,0.298752,0.250350,0.164153,0.100044,0.098350
min,2.905000,3.074000,2.939000,0.292000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.467000,4.628000,4.402250,1.659000,0.657000,1.089500,0.407250,0.355750,0.110000,0.050500
50%,5.514000,5.450000,5.389500,1.918000,0.965000,1.284500,0.637000,0.480000,0.173000,0.082000
75%,6.297500,6.307000,6.170500,2.269000,1.197000,1.467500,0.771750,0.580750,0.243000,0.139000
max,7.632000,7.695000,7.569000,2.961000,1.649000,1.644000,1.030000,0.724000,0.598000,0.457000

``read_csv()`` was adequate to open, but missing values were coded as "999." To recode as NaN, the``na_values=999`` parameter was included within ``pd.read_csv()``.

## Problem 7
Load `data7.xlsx`, which is an Excel file. Keep only the sheet named “Data”. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (2 points)

In [49]:
data7 = pd.read_excel("data7.xlsx", sheet_name="Data") # read in file

display(data7.head(10)) # display first 10 rows
display(data7.tail(10)) # display last 10 rows
display(data7.describe())

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,...,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,...,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357
5,Netherlands,7.441,7.498,7.384,2.448,...,1.488,0.878,0.638,0.333,0.295
6,Canada,7.328,7.421,7.236,2.306,...,1.532,0.896,0.653,0.321,0.291
7,New Zealand,7.324,7.401,7.247,2.156,...,1.601,0.876,0.669,0.365,0.389
8,Sweden,7.314,7.388,7.241,2.217,...,1.501,0.913,0.659,0.285,0.383
9,Australia,7.272,7.358,7.186,2.139,...,1.573,0.910,0.647,0.361,0.302

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
146,Malawi,3.587,3.691,3.482,1.732,...,0.541,0.306,0.531,0.210,0.080
147,Haiti,3.582,3.713,3.451,1.744,...,0.714,0.289,0.025,0.392,0.104
148,Liberia,3.495,3.623,3.368,1.640,...,0.858,0.267,0.419,0.206,0.030
149,Syria,3.462,3.664,3.260,1.244,...,0.382,0.539,0.088,0.376,0.144
150,Rwanda,3.408,3.500,3.317,0.500,...,0.896,0.400,0.636,0.200,0.444
151,Yemen,3.355,3.448,3.262,1.106,...,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,...,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,...,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,...,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,...,0.627,0.145,0.065,0.149,0.076

,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,5.375878,5.478654,5.273090,1.922891,0.887417,1.216571,0.598026,0.456981,0.181571,0.112474
std,1.119507,1.107522,1.132544,0.513760,0.382573,0.300380,0.247925,0.162750,0.098805,0.096362
min,2.905000,3.074000,2.735000,0.292000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.453750,4.589750,4.344750,1.654250,0.616250,1.076750,0.422250,0.358250,0.109500,0.051000
50%,5.378000,5.477500,5.284500,1.908500,0.949500,1.261500,0.644000,0.494000,0.174000,0.082000
75%,6.168500,6.260000,6.051250,2.270250,1.197750,1.463000,0.777250,0.580000,0.242250,0.139000
max,7.632000,7.695000,7.569000,2.961000,1.649000,1.644000,1.030000,0.724000,0.598000,0.457000

Since this file is an Excel spreadsheet, the ``read_excel()`` function opened the file. To specify the sheet within the file, the ``sheet_name="Data"`` parameter delimited which sheet to use, and everything looked normal.

## Problem 8
Load `data8.dta`, which is a Stata 13 file. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (2 points)

In [48]:
data8 = pd.read_stata("data8.dta") # read in file
data8.columns = column_names

display(data8.head(10)) # display first 10 rows
display(data8.tail(10)) # display last 10 rows
display(data8.describe())

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,...,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,...,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357
5,Netherlands,7.441,7.498,7.384,2.448,...,1.488,0.878,0.638,0.333,0.295
6,Canada,7.328,7.421,7.236,2.306,...,1.532,0.896,0.653,0.321,0.291
7,New Zealand,7.324,7.401,7.247,2.156,...,1.601,0.876,0.669,0.365,0.389
8,Sweden,7.314,7.388,7.241,2.217,...,1.501,0.913,0.659,0.285,0.383
9,Australia,7.272,7.358,7.186,2.139,...,1.573,0.910,0.647,0.361,0.302

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
146,Malawi,3.587,3.691,3.482,1.732,...,0.541,0.306,0.531,0.210,0.080
147,Haiti,3.582,3.713,3.451,1.744,...,0.714,0.289,0.025,0.392,0.104
148,Liberia,3.495,3.623,3.368,1.640,...,0.858,0.267,0.419,0.206,0.030
149,Syria,3.462,3.664,3.260,1.244,...,0.382,0.539,0.088,0.376,0.144
150,Rwanda,3.408,3.500,3.317,0.500,...,0.896,0.400,0.636,0.200,0.444
151,Yemen,3.355,3.448,3.262,1.106,...,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,...,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,...,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,...,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,...,0.627,0.145,0.065,0.149,0.076

,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.00000,156.000000,156.000000,156.000000,156.000000
mean,5.375877,5.478654,5.273088,1.922891,0.887417,1.21657,0.598026,0.456981,0.181571,0.112474
std,1.119507,1.107522,1.132544,0.513760,0.382573,0.30038,0.247925,0.162750,0.098805,0.096362
min,2.905000,3.074000,2.735000,0.292000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,4.453750,4.589750,4.344750,1.654250,0.616250,1.07675,0.422250,0.358250,0.109500,0.051000
50%,5.378000,5.477500,5.284500,1.908500,0.949500,1.26150,0.644000,0.494000,0.174000,0.082000
75%,6.168500,6.260000,6.051250,2.270250,1.197750,1.46300,0.777250,0.580000,0.242250,0.139000
max,7.632000,7.695000,7.569000,2.961000,1.649000,1.64400,1.030000,0.724000,0.598000,0.457000

``pd.read_stata("data8.dta")`` was necessary to open the file. The column names were also formatted strangely, so ``data8.columns = column_names`` renamed the columns to ensure parallel formatting.

## Problem 9
Load `data9.sav`, which is an SPSS file. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (2 points)

In [24]:
data9 = pd.read_spss("data9.sav") # read in file
data9.columns = column_names

display(data9.head(10)) # display first 10 rows
display(data9.tail(10)) # display last 10 rows
display(data9.describe())

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,...,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,...,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357
5,Netherlands,7.441,7.498,7.384,2.448,...,1.488,0.878,0.638,0.333,0.295
6,Canada,7.328,7.421,7.236,2.306,...,1.532,0.896,0.653,0.321,0.291
7,New Zealand,7.324,7.401,7.247,2.156,...,1.601,0.876,0.669,0.365,0.389
8,Sweden,7.314,7.388,7.241,2.217,...,1.501,0.913,0.659,0.285,0.383
9,Australia,7.272,7.358,7.186,2.139,...,1.573,0.910,0.647,0.361,0.302

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
146,Malawi,3.587,3.691,3.482,1.732,...,0.541,0.306,0.531,0.210,0.080
147,Haiti,3.582,3.713,3.451,1.744,...,0.714,0.289,0.025,0.392,0.104
148,Liberia,3.495,3.623,3.368,1.640,...,0.858,0.267,0.419,0.206,0.030
149,Syria,3.462,3.664,3.260,1.244,...,0.382,0.539,0.088,0.376,0.144
150,Rwanda,3.408,3.500,3.317,0.500,...,0.896,0.400,0.636,0.200,0.444
151,Yemen,3.355,3.448,3.262,1.106,...,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,...,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,...,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,...,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,...,0.627,0.145,0.065,0.149,0.076

,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,5.375878,5.478654,5.273090,1.922891,0.887417,1.216571,0.598026,0.456981,0.181571,0.112474
std,1.119507,1.107522,1.132544,0.513760,0.382573,0.300380,0.247925,0.162750,0.098805,0.096362
min,2.905000,3.074000,2.735000,0.292000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.453750,4.589750,4.344750,1.654250,0.616250,1.076750,0.422250,0.358250,0.109500,0.051000
50%,5.378000,5.477500,5.284500,1.908500,0.949500,1.261500,0.644000,0.494000,0.174000,0.082000
75%,6.168500,6.260000,6.051250,2.270250,1.197750,1.463000,0.777250,0.580000,0.242250,0.139000
max,7.632000,7.695000,7.569000,2.961000,1.649000,1.644000,1.030000,0.724000,0.598000,0.457000

For this dataset, ``pd.read_spss`` opened the file, and we found that it was in the correct formatting except for the column names, which was easily fixed with ``data9.columns = column_names``. However, to use ``read_spss``, it was  necessary to install ``pyreadstat`` in the terminal.

## Problem 10
Load `data10.xpt`, which is a SAS file. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (If some of the country names display as `b'Finland'`, don't worry aout that.) (2 points)

In [47]:
data10 = pd.read_sas("data10.xpt", encoding = " 'utf-8' ") # read in file
data10.columns = column_names

display(data10.head(10)) # display first 10 rows
display(data10.tail(10)) # display last 10 rows
display(data10.describe())

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,...,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,...,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357
5,Netherlands,7.441,7.498,7.384,2.448,...,1.488,0.878,0.638,0.333,0.295
6,Canada,7.328,7.421,7.236,2.306,...,1.532,0.896,0.653,0.321,0.291
7,New Zealand,7.324,7.401,7.247,2.156,...,1.601,0.876,0.669,0.365,0.389
8,Sweden,7.314,7.388,7.241,2.217,...,1.501,0.913,0.659,0.285,0.383
9,Australia,7.272,7.358,7.186,2.139,...,1.573,0.910,0.647,0.361,0.302

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
146,Malawi,3.587,3.691,3.482,1.732,...,5.410000e-01,0.306,0.531,0.210,0.080
147,Haiti,3.582,3.713,3.451,1.744,...,7.140000e-01,0.289,0.025,0.392,0.104
148,Liberia,3.495,3.623,3.368,1.640,...,8.580000e-01,0.267,0.419,0.206,0.030
149,Syria,3.462,3.664,3.260,1.244,...,3.820000e-01,0.539,0.088,0.376,0.144
150,Rwanda,3.408,3.500,3.317,0.500,...,8.960000e-01,0.400,0.636,0.200,0.444
151,Yemen,3.355,3.448,3.262,1.106,...,1.073000e+00,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,...,9.910000e-01,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,...,6.080000e-01,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,...,5.397605e-79,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,...,6.270000e-01,0.145,0.065,0.149,0.076

,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,1.560000e+02,1.560000e+02,1.560000e+02,1.560000e+02,1.560000e+02,1.560000e+02
mean,5.375878,5.478654,5.273090,1.922891,8.874167e-01,1.216571e+00,5.980256e-01,4.569808e-01,1.815705e-01,1.124744e-01
std,1.119507,1.107522,1.132544,0.513760,3.825727e-01,3.003804e-01,2.479247e-01,1.627499e-01,9.880460e-02,9.636232e-02
min,2.905000,3.074000,2.735000,0.292000,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
25%,4.453750,4.589750,4.344750,1.654250,6.162500e-01,1.076750e+00,4.222500e-01,3.582500e-01,1.095000e-01,5.100000e-02
50%,5.378000,5.477500,5.284500,1.908500,9.495000e-01,1.261500e+00,6.440000e-01,4.940000e-01,1.740000e-01,8.200000e-02
75%,6.168500,6.260000,6.051250,2.270250,1.197750e+00,1.463000e+00,7.772500e-01,5.800000e-01,2.422500e-01,1.390000e-01
max,7.632000,7.695000,7.569000,2.961000,1.649000e+00,1.644000e+00,1.030000e+00,7.240000e-01,5.980000e-01,4.570000e-01

To open the file, ``pd.read_sas()`` is the way to go. But to clean it up, ``encoding = " 'utf-8' "`` removed the " b' ' " that was enclosing each country name, and ``data10.columns = column_names`` renamed the columns.

## Problem 11
Please load the `data11.txt` file, which is a fixed width file. The columns are defined as follows:

| Variable                                   | Width | Start | End |
|--------------------------------------------|-------|-------|-----|
| Country                                    | 24    | 1     | 24  |
| Happiness score                            | 5     | 25    | 29  |
| Whisker-high                               | 5     | 30    | 34  |
| Whisker-low                                | 5     | 35    | 39  |
| Dystopia (1.92) + residual                 | 5     | 40    | 44  |
| Explained by: GDP per capita               | 5     | 45    | 49  |
| Explained by: Social support               | 5     | 50    | 54  |
| Explained by: Healthy life expectancy      | 5     | 55    | 59  |
| Explained by: Freedom to make life choices | 5     | 60    | 64  |
| Explained by: Generosity                   | 5     | 65    | 69  |
| Explained by: Perceptions of corruption    | 5     | 70    | 74  |

Then save the this loaded data frame as a CSV file on your local machine. Be sure to use a unique filename so as not to overwrite any existing files. (5 points)

In [46]:
datawidths = [24, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

data11 = pd.read_fwf("data11.txt", header=None, widths=datawidths, names=column_names) # read in file
display(data11.head(10)) # display first 10 rows
display(data11.tail(10)) # display last 10 rows
display(data11.describe())

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,...,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,...,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357
5,Netherlands,7.441,7.498,7.384,2.448,...,1.488,0.878,0.638,0.333,0.295
6,Canada,7.328,7.421,7.236,2.306,...,1.532,0.896,0.653,0.321,0.291
7,New Zealand,7.324,7.401,7.247,2.156,...,1.601,0.876,0.669,0.365,0.389
8,Sweden,7.314,7.388,7.241,2.217,...,1.501,0.913,0.659,0.285,0.383
9,Australia,7.272,7.358,7.186,2.139,...,1.573,0.910,0.647,0.361,0.302

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
146,Malawi,3.587,3.691,3.482,1.732,...,0.541,0.306,0.531,0.210,0.080
147,Haiti,3.582,3.713,3.451,1.744,...,0.714,0.289,0.025,0.392,0.104
148,Liberia,3.495,3.623,3.368,1.640,...,0.858,0.267,0.419,0.206,0.030
149,Syria,3.462,3.664,3.260,1.244,...,0.382,0.539,0.088,0.376,0.144
150,Rwanda,3.408,3.500,3.317,0.500,...,0.896,0.400,0.636,0.200,0.444
151,Yemen,3.355,3.448,3.262,1.106,...,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,...,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,...,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,...,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,...,0.627,0.145,0.065,0.149,0.076

,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,5.375878,5.478654,5.273090,1.922891,0.887417,1.216571,0.598026,0.456981,0.181571,0.112474
std,1.119507,1.107522,1.132544,0.513760,0.382573,0.300380,0.247925,0.162750,0.098805,0.096362
min,2.905000,3.074000,2.735000,0.292000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.453750,4.589750,4.344750,1.654250,0.616250,1.076750,0.422250,0.358250,0.109500,0.051000
50%,5.378000,5.477500,5.284500,1.908500,0.949500,1.261500,0.644000,0.494000,0.174000,0.082000
75%,6.168500,6.260000,6.051250,2.270250,1.197750,1.463000,0.777250,0.580000,0.242250,0.139000
max,7.632000,7.695000,7.569000,2.961000,1.649000,1.644000,1.030000,0.724000,0.598000,0.457000

Phew. This one was a bit of a doozy. To read the file, we used ``pd.read_fwf()`` with the parameters
``header=None, widths=datawidths, names=column_names`` to move the Finland line into the dataframe and add a header, define the width of each column, and name the columns, respectively, where ``datawidths`` is a list of the length of the data in each column.

## Problem 12
Let's talk ``pickle``. From the Python documentation and the Internet, pickle one of the previously used files. Once it's nice and briny, unpickle it and show its format. Describe what ``pickle`` is and what it does. (OPTIONAL)

In [58]:
import pickle
## code adapted from class notes from summer python class at ucb extension
data4 = pd.read_csv("data4.txt", names=column_names, sep="$") # read in file

try:
    pickled_d4 = open('data4.dump', 'wb')
    
except IOError: 
     
    sys.stderr.write('Error opening employees.dump for write') 
    sys.exit(1)

pkl = pickle.Pickler(pickled_d4) 

pkl.dump(data4) 
pickled_d4.close()

In [60]:
# When it is needed in another file, add code such that the following aspects are included in order:

import pickle

pickled_d4 = open('data4.dump', 'rb')

data4 = pickle.load(pickled_d4)

# From here, you can use indexes to extract specific information from the data.

display(data4.head()) # going back to the format of the above problems to demonstrate unpickling

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,...,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,...,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357

``pickle`` is a bit of an odd bird within Python. Not all object types can be pickled (for example, generator and lambda functions cannot be), and it is not necessarily usable outside Python or cross-compatible among different versions of the language. It works by converting the object in question into bytes (binary form) for more convenient storage using the ``Pickler`` method, and may be used across files.

## Problem 13
On to ``read_HDF``! From the Python documentation and the Internet, describe what ``read_HDF`` is and what it does. (OPTIONAL)

>By what I can gather from various corners of the Internet, read_HDF is meant for .H5 files. These usually contain large amounts of data. Other file formats may be changed into this format using the ``silx`` module, documentation [here](http://www.silx.org/doc/silx/0.7.0/Tutorials/convert.html), and it would appear that, once read in, the file functions similarly to those used above.

## Problem 14
Light as a ``feather``, but with less complex air resistence, the feather object type from Python is another type of serialization function (like the ``pickle`` mentioned above).  From the Python documentation and the Internet, convert one of the previously used files into a feather, and read it in. Describe what a feather is and what it does. (OPTIONAL)

In [61]:
import feather

# We'll use data4 again

dataFrame = pd.DataFrame(data=data4)

dataFrame.to_feather("data4.txt")

readFrame = pd.read_feather("data4.txt", columns=None, use_threads=True)

print(readFrame)

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
ModuleNotFoundError: No module named 'feather'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
AttributeError: 'ModuleNotFoundError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
AssertionError

ModuleNotFoundError: No module named 'feather'

``feather`` type objects are used to format data so that it may be transferred between Python and R. [Source](https://pythontic.com/pandas/serialization/feather)